# Site settings
title: mersidof
email: 
baseurl: ""
url: "http://mersidof.github.io"
github_username:  mersidof
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
